### ISSUE TITLE
Question about float -> decimal conversion

### ISSUE THREAD

**Issue by lukewestby** [cod-technologies/decimal-rs#5]
Hi folks,

I admittedly don't know a lot about floating point numbers so I just wanted to ask if some of the conversion results we are seeing are correct:

- `Decimal::try_from(0.1_f32).unwrap() == Decimal::from_str("0.10000000000000001").unwrap()`
- `Decimal::try_from(0.2_f32).unwrap() == Decimal::from_str("0.20000000000000001").unwrap()`
- `Decimal::try_from(0.3_f32).unwrap() == Decimal::from_str("0.29999999999999999").unwrap()`
- `Decimal::try_from(0.4_f32).unwrap() == Decimal::from_str("0.40000000000000002").unwrap()`

Like I said I don't know much about floating point conversion so if these are the technically correct results we will just account for them in our code but I wanted to check with you first.

Thank you!

**Comment by davidli2010** [comment]
I think it's OK. According to IEEE 754, floating point numbers cannot accurately represent decimal fractions.

```rust
0.10000000000000001_f32 = 0.1
0.20000000000000001_f32 = 0.2
0.29999999999999999_f32 = 0.3
0.40000000000000002_f32 = 0.4
```
