### ISSUE TITLE
Request for Performance Benchmark Comparison with rust_decimal

### ISSUE THREAD

**Issue by pymongo** [cod-technologies/decimal-rs#7]
I am considering using your library for a project that requires precise decimal calculations, and performance is a critical aspect for us. I noticed that `rust_decimal` is most popular decimal library in the Rust ecosystem used for decimal arithmetic.

Would it be possible to provide a benchmark comparison between your library and `rust_decimal`?

Thanks!

**Comment by davidli2010** [comment]
You can see https://github.com/cod-technologies/decimal-bench.
